### ISSUE TITLE
Assess the viability of using cosmovisor for future chain upgrades

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/core#17]
**Problem definition**
It would be nice to be able to use cosmovisor to perform chain upgrades if we are going to be using upgrade handlers anyways, as this would enable a higher degree of automation around the release management process

**Acceptance criteria**
Decide on whether or not this should be implemented

**Additional context**
- [ ] Implement layer 1 dojo for using cosmovisor
- [ ] Speak with validators to confirm if they want to use cosmovisor (questionary)
- [ ] Explore why cosmovisor breaks the binary?
- [ ] Conduct research to determine how this integrates with software research proposals.

**Comment by edk208** [comment]
just a note about this, I've been told by several people that cosmovisor isn't great... I haven't heard why though.  
Terra 2 also states in their upgrades, "Use of cosmovisor is not advised. You should handle this update manually. "
Again, I do not know why.

**Comment by vuong177** [comment]
Cosmovisior is just a tool for changing binary. Yep, validators can handle the upgrade manually.

**Comment by inon-man** [comment]
It is also recommendation not to use automatic upgrade accroding to cosmos docs

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/L1-dojo/issues/2

**Comment by ZaradarBH** [comment]
I dont think we will use it , but I would like to see how it works and figure out what the problems are as I think this feature would be super cool for "automatic updates" which is good for security, obviously it would require that we can make sure its reliable and does not blow up the network :D

**Comment by nghuyenthevinh2000** [comment]
**Cosmovisor potential failure**

1. complicated setting prone to errors.

- To install a previous version, you can specify the version. IMPORTANT: Chains that use Cosmos-SDK v0.44.3 or earlier (eg v0.44.2) and want to use auto-download feature MUST use cosmovisor v0.1.0

- NOTE: we don't recommend using auto-download because it doesn't verify in advance if a binary is available. If there will be any issue with downloading a binary, the cosmovisor will stop and won't restart an App (which could lead to a chain halt).

- I realize that the process of setting up cosmovisor for automatic upgrade bases entirely on validator carefulness and precise coordination from the network which can always go wrong very easily.

2. If the upgrade fails, cosmovisor won't restart the chain. For validator who doesn't understand, cosmovisor can create a false sense of security.

3. Cosmovisor is a wrapper around chain app, it may reduce efficiency
