### ISSUE TITLE
Review Option for Multiple SDR's for Oracle Feeder

### ISSUE THREAD

**Issue by LuncBurner** [classic-terra/core#230]
**Problem definition**
A.E suggested the use of multiple SDR's for use with the Oracle feeder to ensure price stability.  

**Acceptance criteria**
- [x] Review previous Oracle implementation vs. current version
- [x] Review options for multiple SDR sources

**Comment by LuncBurner** [comment]
Previous versions of Oracle Feeder to compare against:

https://github.com/aeuser999/oracle-feeder

https://github.com/aeuser999/tr-oracle-feeder

Both versions derive from this commit from TFL's repo:
git clone https://github.com/terra-money/oracle-feeder
git checkout 5084f8441eb74f518163250ae38837bc2566aebc
     # https://github.com/terra-money/oracle-feeder/commit/5084f8441eb74f518163250ae38837bc2566aebc

**Comment by aeuser999** [comment]
Thank you @LuncBurner .

Just adding this note that I mentioned previously in the [TerraClassic Validator Discord](https://discord.com/channels/984128262311645254/984128262768852994/1108486346433110046):
> You can see the sources here:
>  * CurrencyLayer:
>      * https://currencylayer.com/currencies
>      * Maps XDR to SDR:  https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/CurrencyLayer.ts#L20
>  * Alpha Vantage:
>      * https://www.alphavantage.co/physical_currency_list/
>      * Maps XDR to SDR:  https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/AlphaVantage.ts#L16
> * ExchangeRate:
>     * https://api.exchangerate.host/latest
>     * Maps XDR to SDR:  https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/ExchangeRate.ts#L19
> * Fixer (seems to be the one with MYR problems - best not to have in first position priority):
>     * https://fixer.io/symbols
>     * Maps XDR to SDR:  https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/Fixer.ts#L21

*Fiat Providers (and SDR / XDR) Notes:*
I did find that, on looking at [https://github.com/classic-terra/oracle-feeder/tree/main/price-server/src/provider/fiat/quoter](https://github.com/classic-terra/oracle-feeder/tree/main/price-server/src/provider/fiat/quoter) that the other fiat sources are still in the code base.  

I had wondered if just adding the fiat provider classes configuration into the default.js configuration file would work, and so I tested that (one single entry being tested in fallbackPriority per provider), but it does look like, in some cursory unit testing, that those fiat provider classes need reworking to work with the changes TFL made for Terra v2 (it switched the pair order around).  I did come up with:
* a [partial fix for the CurrencyLayer provider class](https://docs.google.com/document/d/e/2PACX-1vSJvK-_S2zlTLnYBh8loO6pfncAw1DNuHzFGowxGZBfv_k7PUbqMuTq8KbKl3kMDEngKrwqZjjUbjtY/pub) (I did test it functionally, but it is not linted, and I only spot checked the prices).
     * Used prior oracle v2.0.3 default-sample.js config from price-server to add in the fiatProvider section
     * _Needs:_  It does need some conversion of symbol to handle the format that CurrencyLayer returns the data in (similar to the Kraken class fix mentioned below that uses getBaseCurrency, and getQuoteCurrency from 'lib/currency' ).  It does not return any of the fiat data in http://localhost:8532/latest (although it no longer throws an error).
* a [partial fix for the AlphaVantage provider class](https://docs.google.com/document/d/e/2PACX-1vSvNxV1Qbu-vAdXOlQCYSa2gE_Bu-0B_M5E1KaTGXe6QS0u1ZEY3UposO4njDGReZ6-xzexfy3s8o3B/pub) (same as above, tested functionally, not linted, only spot checked).
     * Used prior oracle v2.0.3 default-sample.js config from price-server to add in the fiatProvider section
     * _Needs:_ It does need to limit the calls, getting too many calls warning (instead of correct data).
     * _Needs:_ It appends e-8 (so not a number) for some prices (ie. 6.558095929353e-8 ).
* a [partial fix for the Fixer provider class](https://docs.google.com/document/d/e/2PACX-1vTucjnvoFV85086lRzdVmxqd9DOwpcWT0wPnVLjPZCsf1IPRIc-p7iBb-Jb2pIcbVgwsrsnVkadMeV2/pub) (same as above, tested functionally, not linted, only spot checked).
     * Used prior oracle v2.0.3 default-sample.js config from price-server to add in the fiatProvider section
     * _Needs:_ It appends e-8 (so not a number) for some prices (ie. 6.558095929353e-8 ).


*Crypto Providers Notes:*
I also found that some of the crypto providers in the current default-sample.js config file for the price-server are not working correctly.  I did come up with:
* a [fix for Kraken](https://docs.google.com/document/d/e/2PACX-1vTjySJ6vW924zCwb7RrkdbboJ-crq5ajKBRvLS3T6Uwt98L38vv5o_3gAS-AQkd-OiK1hDeAh5JcGDF/pub) (I did test it functionally, but it is not linted, and I only spot checked the prices).  
     * For it to work, the 'LUNC/USD' and 'USTC/USD' have to be added into the default.js config file in price-server for Kraken.
* Kucoin needs to limit its rate, it was getting (too many requests) error (probably good to implement for all the fiat and crypto provider classes).

When I tested with only a single fallbackPosition for each crypto provider (I am in a restricted zone for Binance, so I could not test that one), only CoinGecko worked (with the exception of the updated Kraken file).  It is probably because the others do not have a LUNC/USD pair (although they have LUNC/USDT or LUNC/USDC or LUNC/BUSD - so they would need to be translated).


I am not sure if any of this is helpful, but wanted to share if helpful.  Since it was just preliminary, unfinished, and tested in a cursory manner, that is the reason I just posted back links to the code mentioned (rather than a PR).

I hope you have a great day today :)

**Comment by alchemist-ti** [comment]
The difference between the previous version and the current version: https://github.com/aeuser999/tr-oracle-feeder/compare/5084f8441eb74f518163250ae38837bc2566aebc...main.

It mainly contains:

* Add DockerFile
* Update dependencies: axios & @terra-money/terra.js
* Update keys encrypt and decrypt
* Refactor configs

**Comment by alchemist-ti** [comment]
@LuncBurner Now classic terra uses https://github.com/classic-terra/oracle-feeder.

Availability of multiple SDR sources:

| source       | URI                   | available |
| -----------| -------------- | --------- |
| ExchangeRate | https://api.exchangerate.host/latest?USD&symbols=XDR,KRW,MNT,EUR,CNY,JPY,GBP,INR,CAD,CHF,HKD,AUD,SGD,THB,SEK,DKK,IDR,PHP,MYR,NOK,TWD | true |
| Frankfurt    | https://api.frankfurter.APP/latest?from=SDR&to=USD  | false        |
| fer.ee       | https://api.fer.ee/latest?base=SDR&to=USD                     | false        |

**Comment by alchemist-ti** [comment]
@aeuser999 Do you know of any other sources of SDR rates?

**Comment by aeuser999** [comment]
> The difference between the previous version and the current version: [aeuser999/tr-oracle-feeder@5084f84...main](https://github.com/aeuser999/tr-oracle-feeder/compare/5084f8441eb74f518163250ae38837bc2566aebc...main).
> 
> It mainly contains:
> 
>     * Add DockerFile
> 
>     * Update dependencies: axios & @terra-money/terra.js
> 
>     * Update keys encrypt and decrypt
> 
>     * Refactor configs

Hi @alchemist-ti ,

I would add in the list that the [older TR oracle version](https://github.com/aeuser999/tr-oracle-feeder) has the SHA256 fix to the keystore:
* [https://github.com/aeuser999/tr-oracle-feeder/commit/a7c35b88493edb30c2d0b5c4ab7d7e4c79fe3e58](https://github.com/aeuser999/tr-oracle-feeder/commit/a7c35b88493edb30c2d0b5c4ab7d7e4c79fe3e58)
* [https://github.com/aeuser999/tr-oracle-feeder/commit/0745b843581f5558923280b5c461bcf852c42665](https://github.com/aeuser999/tr-oracle-feeder/commit/0745b843581f5558923280b5c461bcf852c42665)
* [https://github.com/aeuser999/tr-oracle-feeder/commit/e3258df3c56fac20f66cd5b2fc4e9816d79d06cd](https://github.com/aeuser999/tr-oracle-feeder/commit/e3258df3c56fac20f66cd5b2fc4e9816d79d06cd)
* [https://github.com/aeuser999/tr-oracle-feeder/commit/ba4ac0826d21f77023720a503c76010182873608](https://github.com/aeuser999/tr-oracle-feeder/commit/ba4ac0826d21f77023720a503c76010182873608)

It was one of the enhancements with that particular version.

**Comment by aeuser999** [comment]
> @aeuser999 Do you know of any other sources of SDR rates?

I do notice that the following two sources do not give back SDR (or XDR - XDR being the way foreign exchange price sources will most likely list SDR):
| Source | URL | Response |
|------|-----|------|
| Frankfurter | https://api.frankfurter.APP/latest?from=SDR&to=USD | {"message":"not found"} |
| fer.ee | https://api.fer.ee/latest?base=SDR&to=USD | {"message":"not found"} |

 
There are those with the code already in the base (that are listed in the old TR version's [default-sample.js](https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/config/default-sample.js#L47-L86)), such as:  ['currencylayer'](https://github.com/classic-terra/oracle-feeder/tree/main/price-server/src/provider/fiat/quoter), ['alphavantage'](https://github.com/classic-terra/oracle-feeder/tree/main/price-server/src/provider/fiat/quoter), ['fixer'](https://github.com/classic-terra/oracle-feeder/tree/main/price-server/src/provider/fiat/quoter), ['exchangerate'](https://github.com/classic-terra/oracle-feeder/tree/main/price-server/src/provider/fiat/quoter) (bandprotocol stopped supporting SDR/XDR it appears, and the [api endpoint listed in the old TR code](https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/BandProtocol.ts#LL23C26-L23C88) for bandprotocol does not work for me)(I notice bandprotocol was removed from the newer TFL and L1JTF version).  

Fixer has had issues with MYR, and so it may be good if we can find other sources to use than Fixer.  Or, maybe filter out MYR for Fixer in default-sample.js, similar to how [SDR is filtered out from Frankfurter and Fer](https://github.com/classic-terra/oracle-feeder/blob/main/price-server/config/default-sample.js#L615-L622), so that another sources prices for MYR, rather than Fixer's, prevail, or maybe better fix the logic so that if one source's price for an asset are more than 50% off from other sources then filter out that source's price for the asset from consideration among the other sources' prices for that asset in the code itself (ie. move to the next source that has pricing in the priority list).  
* Attaching a screenshot of fixer's last MYR failure, and [here is a link](https://classic-agora.terra.money/t/remove-and-secure-the-stablecoin-terra-market-swap/47177/80) to the first MYR failure we experienced after May 2022 and fixer as a probable source for that as well.).

Also, I don't know if you saw this already, just passing it along if helpful (disregard if not), SDR from default-sample.js is [translated to XDR in the code](https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/CurrencyLayer.ts#L20) for sources that list it as XDR, and then [translates XDR back to SDR after pricing](https://github.com/aeuser999/tr-oracle-feeder/blob/main/price-server/src/provider/fiat/quoter/CurrencyLayer.ts#L43) (so that it will work to use SDR in the default-sample.js).  

But, **to answer your direct question** "Do you know of any other sources of SDR rates", the problem is coming up with free, yet reliable, sources for SDR / XDR, that update fiat prices regularly.  Here are some providers, in addition to the ones listed above, that have SDR / XDR (although paid - but do have a free subscription for testing purposes with rate limit):
* https://api.fastforex.io/fetch-all?from=USD&api_key=demo
     * Price $9 a month [https://www.fastforex.io/#Pricing](https://www.fastforex.io/#Pricing)
* https://api.apilayer.com/exchangerates_data/latest
     * Could not get the [actual ExchangeRates API](https://exchangeratesapi.io) to work for testing, so listed it through the [API Layer site](https://apilayer.com/marketplace/exchangerates_data-api)
     * Price [$39.99 a month](https://apilayer.com/marketplace/exchangerates_data-api)
* https://api.fxapi.com/v1/latest
     * Price [$34.99 a month](https://fxapi.com/pricing/)
* https://api.currencyapi.com/v3/latest
     * Same CEO as fxapi.com, but it does look like it returns a different data set
     * Price [$34.99 a month](https://currencyapi.com/pricing/)
* Didn't list openexchangerates.org , although it also has SDR / XDR, since it only [updates at best every 10 minutes](https://openexchangerates.org/faq#how-often)

I hope that helps out a little bit, and that you have a great day today :)

**Comment by LuncBurner** [comment]
@aeuser999 @alchemist-ti Excellent collaboration.  If we need to pay a small monthly fee to a site that produces another source for SDR and it is advantageous to us, I would think we could go ahead and purchase a 2-year subscription to such a service.

**Comment by aeuser999** [comment]
> @aeuser999 @alchemist-ti Excellent collaboration. If we need to pay a small monthly fee to a site that produces another source for SDR and it is advantageous to us, I would think we could go ahead and purchase a 2-year subscription to such a service.

Hi @LuncBurner ,

That sounds awesome.  I may be missing something (if so, just disregard), but the cost has traditionally been for validators to pay at signup (at least, it is mentioned in earlier versions of the default-sample.js file, and traditionally validators have picked up their own subscription costs).  For instance CurrencyLayer (Business), AlphaVantage (Premium), and Fixer (Professional) each have a subscription cost to provide an appropriate amount of requests per month without rate limiting.  The newer ones I mentioned [above](https://github.com/classic-terra/core/issues/230#issuecomment-1581656507) have the same types of plans for enough requests per month.  But, it is true, having an enterprise plan to make sure validators are providing varied sources, rather than just sticking with the free sources, may be something to consider.

Each of the API services have a free plan that should work for testing (normally 500 or so requests), although you are right that more extensive testing may require a paid plan to make sure not to hit the limit on requests in testing.

As a thought:  Even if a validator picked at least 3 good paid sources (to add to the free ExchangeRate, and other non-SDR free sources), it would give a good variety for which 3 sources they can pick from.

Don't know if that helps (again, just disregard if not, or if I misunderstood).

I hope you are having an awesome day today :)

**Comment by alchemist-ti** [comment]
@aeuser999 thanks for your detailed elaboration.

> As a thought: Even if a validator picked at least 3 good paid sources (to add to the free ExchangeRate, and other non-SDR free fiat sources), it would give a good variety for which 3 sources they can pick from (if we had each of these fiat providers - reworking those that still exist in the code base, and then possibly using those classes as a template to add in the new fiat providers?). Just a thought though...

That's good advice.

As you comment here https://github.com/classic-terra/core/issues/230#issuecomment-1565535456, 'currencylayer', 'alphavantage', 'fixer' are also available now. Seems we can revert some code to support them quickly, and the traditionally validators can use them via the previous API keys.

In the long run, we can support more sources you mentioned.

**Comment by aeuser999** [comment]
> @aeuser999 I re-supported currencylayer and fixer in [classic-terra/oracle-feeder#16](https://github.com/classic-terra/oracle-feeder/pull/16), can you help review it?

Sorry, I have not had the chance to be able to do this yet.  I will try to make some time on Saturday to look at it.  Thank you so much for all your work in adding those - that is awesome :)
