### ISSUE TITLE
Deploy v1.0.5 to validators, CEXs, full nodes

### ISSUE THREAD

**Issue by edk208** [classic-terra/core#61]

**Comment by LuncBurner** [comment]
Ed addressing concern raised on Luna Classic validator discord:
"I have raised your and Jacob's concern to our expert cosmos dev. His response is that the v1.0.5 upgrade is fine, and the concern about the seven terrabytes of historic state is not an issue. In their words, the full state test is not necessary here because the app hash represents the state.
 that being said, there is a known separate issue with the full state of the chain that I believe Jacob's is alluding to. This includes possible corrupted archives by an indexing bug in tendermint 34.14. This predates the depeg and was an issue even before the death spiral of may 2022. If you have ever tried to sync from genesis, you probably found you could not. We believe we have found and possibly fixed this issue and are testing a full node archive release. Note, syncing from genesis means you do not use any snapshots and start from the onset of columbus-5. (This process takes several weeks to complete)"  @inon-man Please confirm.

**Comment by inon-man** [comment]
> Ed addressing concern raised on Luna Classic validator discord:
> "I have raised your and Jacob's concern to our expert cosmos dev. His response is that the v1.0.5 upgrade is fine, and the concern about the seven terrabytes of historic state is not an issue. In their words, the full state test is not necessary here because the app hash represents the state.
>  that being said, there is a known separate issue with the full state of the chain that I believe Jacob's is alluding to. This includes possible corrupted archives by an indexing bug in tendermint 34.14. This predates the depeg and was an issue even before the death spiral of may 2022. If you have ever tried to sync from genesis, you probably found you could not. We believe we have found and possibly fixed this issue and are testing a full node archive release. Note, syncing from genesis means you do not use any snapshots and start from the onset of columbus-5. (This process takes several weeks to complete)"  @inon-man Please confirm this statement by Ed is accurate, and that the 1.0.5 release has been reviewed sufficiently by yourself, and that you feel it is ready and should be implemented by validators.

This is all true and I will personally spin up a new full node from the genesis of columbus-5 to make sure that the release is good to go.
